# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Download\Python\Git\Project\demo221109-ArkNights\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Token = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Token.setObjectName("lineEdit_Token")
        self.horizontalLayout.addWidget(self.lineEdit_Token)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_Get = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Get.setObjectName("pushButton_Get")
        self.gridLayout_2.addWidget(self.pushButton_Get, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_FilesPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_FilesPath.setObjectName("lineEdit_FilesPath")
        self.horizontalLayout_2.addWidget(self.lineEdit_FilesPath)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.pushButton_Analyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Analyse.setObjectName("pushButton_Analyse")
        self.gridLayout_3.addWidget(self.pushButton_Analyse, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "明日方舟寻访信息获取控制台"))
        self.groupBox.setTitle(_translate("MainWindow", "获取寻访信息并保存"))
        self.label.setText(_translate("MainWindow", "你的Token"))
        self.pushButton_Get.setText(_translate("MainWindow", "开始"))
        self.groupBox_2.setTitle(_translate("MainWindow", "读取寻访信息文件并分析"))
        self.label_2.setText(_translate("MainWindow", "文件路径"))
        self.pushButton_Analyse.setText(_translate("MainWindow", "开始"))
