# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Download\Python\Git\Project\demo221109-ArkNights\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Token = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Token.setObjectName("lineEdit_Token")
        self.horizontalLayout.addWidget(self.lineEdit_Token)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_Get = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Get.setObjectName("pushButton_Get")
        self.gridLayout_2.addWidget(self.pushButton_Get, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_FilesPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_FilesPath.setObjectName("lineEdit_FilesPath")
        self.horizontalLayout_2.addWidget(self.lineEdit_FilesPath)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.pushButton_Analyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Analyse.setObjectName("pushButton_Analyse")
        self.gridLayout_3.addWidget(self.pushButton_Analyse, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_merge = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.gridLayout_4.addWidget(self.pushButton_merge, 0, 1, 1, 1)
        self.textEdit_merge_filepath = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_merge_filepath.setObjectName("textEdit_merge_filepath")
        self.gridLayout_4.addWidget(self.textEdit_merge_filepath, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "明日方舟寻访信息获取控制台"))
        self.groupBox.setTitle(_translate("MainWindow", "获取寻访信息并保存"))
        self.label.setText(_translate("MainWindow", "你的Token"))
        self.pushButton_Get.setText(_translate("MainWindow", "开始"))
        self.groupBox_2.setTitle(_translate("MainWindow", "读取寻访信息文件并分析"))
        self.label_2.setText(_translate("MainWindow", "文件路径"))
        self.pushButton_Analyse.setText(_translate("MainWindow", "开始"))
        self.groupBox_3.setTitle(_translate("MainWindow", "寻访信息文件合并"))
        self.pushButton_merge.setText(_translate("MainWindow", "开始"))
        self.textEdit_merge_filepath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">路径之间用|隔开！</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "操作台"))
